[gamevals.synth]
thieving_stunned = 2727

[gamevals.category]
man = 266
woman = 492
farmer = 498
master_farmer = 641
cave_goblin = 373
guard = 470
ardougne_guard = 1732
warrior = 1728
knight_of_ardougne = 1731
knight_of_ardougne_west = 1727
knight_of_varlamore = 1977
paladin = 1729
paladin_west = 1726
gnome = 354
hero = 1730
vyre = 1451
elf = 1392
tzhaar_hur = 431
varlamore_farmer = 1987
kastori_farmer = 2255
varlamore_master_farmer = 1988
kastori_master_farmer = 2256
ham_storeroom_guard = 619
varlamore_tourist = 1986
salvager = 2120
pirate_thieving = 2358
varlamore_citizen = 1952
varlamore_citizen_poor = 1981
varlamore_citizen_rich = 1984
aldarin_citizen_poor = 2110
aldarin_citizen = 2111
aldarin_citizen_rich = 2112
auburnvale_citizen = 2243
auburnvale_citizen_rich = 2244
kastori_citizen = 2252
kastori_citizen_rich = 2253
tal_teklan_citizen = 2257
tal_teklan_citizen_rich = 2258

[gamevals.varp]
gloves_of_silence_failures = 64000
dodgy_necklace_uses = 64001

[gamevals.dbtable]
thieving_pickpocket = 64000
thieving_stall = 64001

[gamevals.dbrow]
thieving_pickpocket_citizen = 63860
thieving_pickpocket_farmer = 63861
thieving_pickpocket_ham_member = 63862
thieving_pickpocket_ham_member_2 = 63863
thieving_pickpocket_ham_guard = 63864
thieving_pickpocket_tourist = 63865
thieving_pickpocket_salvager = 63866
thieving_pickpocket_warrior = 63867
thieving_pickpocket_rogue = 63868
thieving_pickpocket_cave_goblin = 63869
thieving_pickpocket_master_farmer = 63870
thieving_pickpocket_guard = 63871
thieving_pickpocket_fremennik_citizen = 63872
thieving_pickpocket_desert_bandit = 63873
thieving_pickpocket_knight = 63874
thieving_pickpocket_pirate = 63875
thieving_pickpocket_watchman = 63876
thieving_pickpocket_paladin = 63877
thieving_pickpocket_gnome = 63878
thieving_pickpocket_hero = 63879
thieving_pickpocket_vyre = 63880
thieving_pickpocket_elf = 63881
thieving_pickpocket_elf_lletya = 63882
thieving_pickpocket_tzhaar_hur = 63883
thieving_stall_seed = 63884
thieving_stall_wine = 63885
thieving_stall_ardougne_baker = 63820
thieving_stall_varrock_tea = 63821
thieving_stall_ardougne_silk = 63822
thieving_stall_ardougne_fur = 63823
thieving_stall_ardougne_silver = 63824
thieving_stall_ardougne_spice = 63825
thieving_stall_ardougne_gem = 63826
thieving_stall_prif_silk = 63827
thieving_stall_prif_silver = 63828
thieving_stall_prif_spice = 63829
thieving_stall_prif_gem = 63830
thieving_stall_rellekka_fish = 63831
thieving_stall_rellekka_fur = 63832
thieving_stall_miscellania_fish = 63833
thieving_stall_miscellania_veg = 63834
thieving_stall_etceteria_fish = 63835
thieving_stall_etceteria_veg = 63836
thieving_stall_keldagrim_bakery = 63837
thieving_stall_keldagrim_crafting = 63838
thieving_stall_keldagrim_crossbow = 63839
thieving_stall_keldagrim_silver = 63840
thieving_stall_keldagrim_gem = 63841
thieving_stall_hosidius_bread = 63842
thieving_stall_hosidius_fruit = 63843
thieving_stall_warrens_fish = 63844
thieving_stall_fortis_baker = 63845
thieving_stall_fortis_silk = 63846
thieving_stall_fortis_fur = 63847
thieving_stall_fortis_spice = 63848
thieving_stall_fortis_gem = 63849
thieving_pickpocket_workman = 63850
thieving_pickpocket_bearded_bandit = 63851
thieving_pickpocket_wealthy_citizen = 63852
thieving_pickpocket_pollnivneach_bandit = 63853
thieving_pickpocket_menaphite_thug = 63854
