package org.alter.plugins.content.mechanics.prayer

/**
 * @author Tom <rspsmods@gmail.com>
 */
enum class Prayer(
    val named: String,
    val child: Int,
    val quickPrayerSlot: Int,
    val varbit: String,
    val level: Int,
    val defenceLevel: Int = 1,
    val sound: Int,
    val drainEffect: Int,
    val group: PrayerGroup?,
    vararg val overlap: PrayerGroup,
) {
    THICK_SKIN(
        named = "Thick Skin",
        child = 9,
        quickPrayerSlot = 0,
        varbit = "varbits.prayer_thickskin",
        level = 1,
        sound = 2690,
        drainEffect = 3,
        group = PrayerGroup.DEFENCE,
        overlap = arrayOf(PrayerGroup.COMBAT),
    ),

    BURST_OF_STRENGTH(
        named = "Burst of Strength",
        child = 10,
        quickPrayerSlot = 1,
        varbit = "varbits.prayer_burstofstrength",
        level = 4,
        sound = 2688,
        drainEffect = 3,
        group = PrayerGroup.STRENGTH,
        overlap = arrayOf(PrayerGroup.RANGED, PrayerGroup.MAGIC, PrayerGroup.COMBAT),
    ),

    CLARITY_OF_THOUGHT(
        named = "Clarity of Thought",
        child = 11,
        quickPrayerSlot = 2,
        varbit = "varbits.prayer_clarityofthought",
        level = 7,
        sound = 2664,
        drainEffect = 3,
        group = PrayerGroup.ATTACK,
        overlap = arrayOf(PrayerGroup.RANGED, PrayerGroup.MAGIC, PrayerGroup.COMBAT),
    ),

    SHARP_EYE(
        named = "Sharp Eye",
        child = 27,
        quickPrayerSlot = 18,
        varbit = "varbits.prayer_sharpeye",
        level = 8,
        sound = 2685,
        drainEffect = 3,
        group = PrayerGroup.RANGED,
        overlap = arrayOf(PrayerGroup.ATTACK, PrayerGroup.STRENGTH, PrayerGroup.MAGIC, PrayerGroup.COMBAT),
    ),

    MYSTIC_WILL(
        named = "Mystic Will",
        child = 30,
        quickPrayerSlot = 19,
        varbit = "varbits.prayer_mysticwill",
        level = 9,
        sound = 2670,
        drainEffect = 3,
        group = PrayerGroup.MAGIC,
        overlap = arrayOf(PrayerGroup.ATTACK, PrayerGroup.STRENGTH, PrayerGroup.RANGED, PrayerGroup.COMBAT),
    ),

    ROCK_SKIN(
        named = "Rock Skin",
        child = 12,
        quickPrayerSlot = 3,
        varbit = "varbits.prayer_rockskin",
        level = 10,
        sound = 2684,
        drainEffect = 6,
        group = PrayerGroup.DEFENCE,
        overlap = arrayOf(PrayerGroup.COMBAT),
    ),

    SUPERHUMAN_STRENGTH(
        named = "Superhuman Strength",
        child = 13,
        quickPrayerSlot = 4,
        varbit = "varbits.prayer_superhumanstrength",
        level = 13,
        sound = 2689,
        drainEffect = 6,
        group = PrayerGroup.STRENGTH,
        overlap = arrayOf(PrayerGroup.RANGED, PrayerGroup.MAGIC, PrayerGroup.COMBAT),
    ),

    IMPROVED_REFLEXES(
        named = "Improved Reflexes",
        child = 14,
        quickPrayerSlot = 5,
        varbit = "varbits.prayer_improvedreflexes",
        level = 16,
        sound = 2662,
        drainEffect = 6,
        group = PrayerGroup.ATTACK,
        overlap = arrayOf(PrayerGroup.RANGED, PrayerGroup.MAGIC, PrayerGroup.COMBAT),
    ),

    RAPID_RESTORE(
        named = "Rapid Restore",
        child = 15,
        quickPrayerSlot = 6,
        varbit = "varbits.prayer_rapidrestore",
        level = 19,
        sound = 2679,
        drainEffect = 1,
        group = null,
        overlap = arrayOf(),
    ),

    RAPID_HEAL(
        named = "Rapid Heal",
        child = 16,
        quickPrayerSlot = 7,
        varbit = "varbits.prayer_rapidheal",
        level = 22,
        sound = 2678,
        drainEffect = 2,
        group = null,
        overlap = arrayOf(),
    ),

    PROTECT_ITEM(
        named = "Protect Item",
        child = 17,
        quickPrayerSlot = 8,
        varbit = "varbits.prayer_protectitem",
        level = 25,
        sound = 1982,
        drainEffect = 2,
        group = null,
        overlap = arrayOf(),
    ),

    HAWK_EYE(
        named = "Hawk Eye",
        child = 28,
        quickPrayerSlot = 20,
        varbit = "varbits.prayer_hawkeye",
        level = 26,
        sound = 2666,
        drainEffect = 6,
        group = PrayerGroup.RANGED,
        overlap = arrayOf(PrayerGroup.ATTACK, PrayerGroup.STRENGTH, PrayerGroup.MAGIC, PrayerGroup.COMBAT),
    ),

    MYSTIC_LORE(
        named = "Mystic Lore",
        child = 31,
        quickPrayerSlot = 21,
        varbit = "varbits.prayer_mysticlore",
        level = 27,
        sound = 2668,
        drainEffect = 6,
        group = PrayerGroup.MAGIC,
        overlap = arrayOf(PrayerGroup.ATTACK, PrayerGroup.STRENGTH, PrayerGroup.RANGED, PrayerGroup.COMBAT),
    ),

    STEEL_SKIN(
        named = "Steel Skin",
        child = 18,
        quickPrayerSlot = 9,
        varbit = "varbits.prayer_steelskin",
        level = 28,
        sound = 2687,
        drainEffect = 12,
        group = PrayerGroup.DEFENCE,
        overlap = arrayOf(PrayerGroup.COMBAT),
    ),

    ULTIMATE_STRENGTH(
        named = "Ultimate Strength",
        child = 19,
        quickPrayerSlot = 10,
        varbit = "varbits.prayer_ultimatestrength",
        level = 31,
        sound = 2691,
        drainEffect = 12,
        group = PrayerGroup.STRENGTH,
        overlap = arrayOf(PrayerGroup.RANGED, PrayerGroup.MAGIC, PrayerGroup.COMBAT),
    ),

    INCREDIBLE_REFLEXES(
        named = "Incredible Reflexes",
        child = 20,
        quickPrayerSlot = 11,
        varbit = "varbits.prayer_incrediblereflexes",
        level = 34,
        sound = 2667,
        drainEffect = 12,
        group = PrayerGroup.ATTACK,
        overlap = arrayOf(PrayerGroup.RANGED, PrayerGroup.MAGIC, PrayerGroup.COMBAT),
    ),

    PROTECT_FROM_MAGIC(
        named = "Protect from Magic",
        child = 21,
        quickPrayerSlot = 12,
        varbit = "varbits.prayer_protectfrommagic",
        level = 37,
        sound = 2675,
        drainEffect = 12,
        group = PrayerGroup.OVERHEAD,
        overlap = arrayOf(),
    ),

    PROTECT_FROM_MISSILES(
        named = "Protect from Missiles",
        child = 22,
        quickPrayerSlot = 13,
        varbit = "varbits.prayer_protectfrommissiles",
        level = 40,
        sound = 2677,
        drainEffect = 12,
        group = PrayerGroup.OVERHEAD,
        overlap = arrayOf(),
    ),

    PROTECT_FROM_MELEE(
        named = "Protect from Melee",
        child = 23,
        quickPrayerSlot = 14,
        varbit = "varbits.prayer_protectfrommelee",
        level = 43,
        sound = 2676,
        drainEffect = 12,
        group = PrayerGroup.OVERHEAD,
        overlap = arrayOf(),
    ),

    EAGLE_EYE(
        named = "Eagle Eye",
        child = 29,
        quickPrayerSlot = 22,
        varbit = "varbits.prayer_eagleeye",
        level = 44,
        sound = 2665,
        drainEffect = 12,
        group = PrayerGroup.RANGED,
        overlap = arrayOf(PrayerGroup.ATTACK, PrayerGroup.STRENGTH, PrayerGroup.MAGIC, PrayerGroup.COMBAT),
    ),

    MYSTIC_MIGHT(
        named = "Mystic Might",
        child = 32,
        quickPrayerSlot = 23,
        varbit = "varbits.prayer_mysticmight",
        level = 45,
        sound = 2669,
        drainEffect = 12,
        group = PrayerGroup.MAGIC,
        overlap = arrayOf(PrayerGroup.ATTACK, PrayerGroup.STRENGTH, PrayerGroup.RANGED, PrayerGroup.COMBAT),
    ),

    RETRIBUTION(
        named = "Retribution",
        child = 24,
        quickPrayerSlot = 15,
        varbit = "varbits.prayer_retribution",
        level = 46,
        sound = 2682,
        drainEffect = 3,
        group = PrayerGroup.OVERHEAD,
        overlap = arrayOf(),
    ),

    REDEMPTION(
        named = "Redemption",
        child = 25,
        quickPrayerSlot = 16,
        varbit = "varbits.prayer_redemption",
        level = 49,
        sound = 2680,
        drainEffect = 6,
        group = PrayerGroup.OVERHEAD,
        overlap = arrayOf(),
    ),

    SMITE(
        named = "Smite",
        child = 26,
        quickPrayerSlot = 17,
        varbit = "varbits.prayer_smite",
        level = 52,
        sound = 2686,
        drainEffect = 18,
        group = PrayerGroup.OVERHEAD,
        overlap = arrayOf(),
    ),

    PRESERVE(
        named = "Preserve",
        child = 37,
        quickPrayerSlot = 28,
        varbit = "varbits.prayer_preserve",
        level = 55,
        sound = 3825,
        drainEffect = 3,
        group = null,
        overlap = arrayOf(),
    ),

    CHIVALRY(
        named = "Chivalry",
        child = 34,
        quickPrayerSlot = 25,
        varbit = "varbits.prayer_chivalry",
        level = 60,
        defenceLevel = 65,
        sound = 3826,
        drainEffect = 24,
        group = PrayerGroup.COMBAT,
        overlap = arrayOf(PrayerGroup.ATTACK, PrayerGroup.STRENGTH, PrayerGroup.DEFENCE, PrayerGroup.RANGED, PrayerGroup.MAGIC),
    ),

    PIETY(
        named = "Piety",
        child = 35,
        quickPrayerSlot = 26,
        varbit = "varbits.prayer_piety",
        level = 70,
        defenceLevel = 70,
        sound = 3825,
        drainEffect = 24,
        group = PrayerGroup.COMBAT,
        overlap = arrayOf(PrayerGroup.ATTACK, PrayerGroup.STRENGTH, PrayerGroup.DEFENCE, PrayerGroup.RANGED, PrayerGroup.MAGIC),
    ),

    RIGOUR(
        named = "Rigour",
        child = 33,
        quickPrayerSlot = 24,
        varbit = "varbits.prayer_rigour",
        level = 74,
        defenceLevel = 70,
        sound = 3825,
        drainEffect = 24,
        group = PrayerGroup.COMBAT,
        overlap = arrayOf(PrayerGroup.ATTACK, PrayerGroup.STRENGTH, PrayerGroup.DEFENCE, PrayerGroup.RANGED, PrayerGroup.MAGIC),
    ),

    AUGURY(
        named = "Augury",
        child = 36,
        quickPrayerSlot = 27,
        varbit = "varbits.prayer_augury",
        level = 77,
        defenceLevel = 70,
        sound = 3825,
        drainEffect = 24,
        group = PrayerGroup.COMBAT,
        overlap = arrayOf(PrayerGroup.ATTACK, PrayerGroup.STRENGTH, PrayerGroup.DEFENCE, PrayerGroup.RANGED, PrayerGroup.MAGIC),
    ),
    ;

    companion object {
        val values = enumValues<Prayer>()
    }
}
